### ISSUE TITLE
Gallery URLs don't work properly anymore after upgrade to 2.1.1 PL

### ISSUE THREAD

**Issue by Martijn1981** [splittingred/Gallery#102]
After having a site upgraded to MODX 2.1.1 PL, the Gallery snippet has suddenly stopped working properly.

I'm using several Gallery chunks on a page, which are being outputted through getResources. Here's the code for the chunk:

<pre>
  [[!Gallery?
    &album=`[[+gallery_album]]`
    &thumbWidth=`150`
    &thumbHeight=`125`
    &useCss=`0`
  ]]      
</pre>

Now, after the upgrade, the phpThumb function of the thumbnails and the bigger images don't seem to work properly anymore! Images aren't visible and when I click on a link that should lead to one of them, all I'm getting is this message:

<pre>
{"success":false,"message":"Access denied.","total":0,"data":[],"object":[]}
</pre>

I've noticed that thumbnails stopped appearing in the Gallery TV and in the albums itself. New images uploaded in the Gallery component are blank as well. I'm using the latest Gallery and MODX version. The problems occured after upgrading to 2.1.1 PL. It somehow seems that the phpThumb function of Gallery has been denied access to the directories or something like that?

By the way, I'm using the :phpthumbof filter on other pages and it works fine there. Also, there are no problems with regular Image TVs and Filemanager thumbnails. The problem seems to lie with only the phpthumb function "inside" Gallery.

**Comment by Martijn1981** [comment]
Also, in the system settings:
- gallery.phpthumb_path leads to /var/www/vhosts/[PRIVATE].nl/httpdocs/assets/components/phpthumb/
- gallery.phpthumb_url leads to /assets/components/phpthumb/

Shouldn't that be /phpthumbof/ in both cases? I've already tried changing them, but no such luck.

Perthaps the phpthumb function of Gallery hasn't been upgraded to 2.1.1 yet?

**Comment by oksushi** [comment]
I also had this behaviour. 

When I view the path I see the following:

{"success":false,"message":"Access denied.","total":0,"data":[],"object":[]}

**Comment by hurby** [comment]
In my case the problem is there in the front-end as well as in the backend. 
On all gallery related elements the thump is gone. Big ones in front end, slider images, small one's coming from tv's, the tv's itself, the imagelist thump. all are broken.

Everything was fine till updating from 2.0.1  to  2.1.1.
Latest versions of Gallery, no thump-off installed.

Reinstalling Gallery, re-uploading the files, new image import, running setup again, clearing the cache, chanching mgn lexicon, prepending url to thump on/off, removing / in the starting path of Gallery, Nothing helps.

This is a mayor website killer. Hope you solve it soon

**Comment by davidpede** [comment]
Hi,

I have the exact same problem as refered to above. No output frontend or backend in MODx ver 2.1.1 but works fine once I rolled it back to 2.1.0.

I also see the following viewing the direct url:
{"success":false,"message":"Access denied.","total":0,"data":[],"object":[]}

As mentioned, a total website killer.

**Comment by Martijn1981** [comment]
Agreed. I do hope this is more of a Gallery issue than a MODX issue, because I upgraded to 2.1.1 for the fix of the template change bug. I do hope I can keep 2.1.1 running.

**Comment by splittingred** [comment]
Fixed. Stop being so dramatic, guys. :P

**Comment by Martijn1981** [comment]
You're lightning fast. Shaun. My compliments and thanks!

**Comment by davidpede** [comment]
lol! Thanks Red, much appreciated

**Comment by hurby** [comment]
Splittingred my main man!

**Comment by Martijn1981** [comment]
Shaun, it's not solved! LOL. The images only appear when you're logged in. When you're logged out. They disappear again. Could you take another look at it please?

**Comment by davidpede** [comment]
Thanks Shaun, working great.

**Comment by oksushi** [comment]
<3

Cheers Shaun!

**Comment by themca** [comment]
Sry i think i am too stupid for that...
 I upgraded to gallery versio 1.2.1 and i still get the {"success":false,"message":"Access denied.","total":0,"data":[],"object":[]} error oO so could you be so kind and help me! (I'm using modx revo 2.1.1, php 5.2)

if you need a link plz feel free to contact me via git-hub!

Regards
Marc
